### ISSUE TITLE
Uppercase roman numerals in Libertinus Sans Italic, Bold and Bold Italic have wrong form

### ISSUE THREAD

**Issue by thommitsch** [khaledhosny/libertinus#105]
The uppercase roman numerals 0x2160 - 0x216F in sans italic, bold and bold italic appear to be adapted from the serif font instead of the sans serif. The lowercase numerals 0x2170 - 0x217F are correct.

![grafik](https://user-images.githubusercontent.com/33422637/32504320-caa0e43c-c3df-11e7-964f-2a45ebfde50f.png)

**Comment by alerque** [comment]
Just for the record, there is no Libertinus Sans Bold Italic. What is screen shoted in this issue is an automatically slanted version of the Bold style. Note this is a slant, not an actual italic.

In LaTeX you can one-up this by applying a FakeBold property to the Italic rather than a FakeSlant to the Bold, but not all software gives you that flexibility.
