### ISSUE TITLE
math bold font

### ISSUE THREAD

**Issue by ArTourter** [khaledhosny/libertinus#20]
Hi
would it be possible to have a libertinus math bold font?

**Comment by khaledhosny** [comment]
Sure, at one point.

**Comment by khaledhosny** [comment]
Closed by accident.

**Comment by MaxNoe** [comment]
:+1:

Without the bold font, the usage of this nice font is not really possible for me and i thonk most physicists and mathematicians.

**Comment by khaledhosny** [comment]
Do you really need a bold math font or just bold math alphabets? The later are mostly supported and should work fine.

**Comment by MaxNoe** [comment]
Ah, sorry. So stuff like `\symbf{A}` works?

**Comment by khaledhosny** [comment]
Yes.

**Comment by MaxNoe** [comment]
Great!

**Comment by elgor** [comment]
Thanks for the information! 

I found that the command `\boldsymbol` will have no effect with unicode-math. However, `\symbf` produces upright bold symbols and I needed the italic shape. I solved the problem with the ISO option from the unicode-math package:
```latex 
\setmathfont[bold-style=ISO]{Libertinus Math}
```
After that `\symbf` produces italic bold and `\mathbf` produces upright bold.
Just in case someone comes across the same problem.

**Comment by khaledhosny** [comment]
I’m not creating an all-bold math font after all since its use is very niche, and bold math alphabets are already present in the font.

**Comment by alerque** [comment]
@fermifunktion I'm glad you like it...

There is no all bold Math font variant (nor are there any plans for one) because that is not how Math fonts typically work. Instead of having a font face with variants for different weights and styles math fonts have separate glyphs for bold characters, italic characters, double-line characters, etc.

If you want the overall weight of a font to be heavier in LaTeX look into packages that artificially add weight to your output. I think there is a way to do this with `\usepackage{pdfrender}` and boosting the `LineWidth` value. Such workarounds are out of scope for this font project though. You should look for and/or ask about details on [TeX TopAnswers](https://topanswers.xyz/tex) or [TeX StackExchange](https://tex.stackexchange.com.)

Also if you have new questions about this font please open new issues, posting comments on old closed ones isn't appropriate.

**Comment by khaledhosny** [comment]
Fontspec package has FakeBold and AutoFakeBold options which should be helpful here.
