### ISSUE TITLE
“Qu” ligature not working with LuaLaTeX

### ISSUE THREAD

**Issue by svitalsky** [khaledhosny/libertinus#21]
With Linux Libertine, Qu ligature (as in Quasi-) works both with XeLaTeX and LuaLaTeX, with Libertinus however it only works with XeTeX. Other ligatures work fine with both engines (see the picture made with LuaLaTeX).

![ligatures](https://cloud.githubusercontent.com/assets/17103067/12869840/f70003ee-cd2a-11e5-9c22-91a03cb166fc.png)

I am using the current version from TeXLive 2015, i.e. 6.2, with last record in the changelog from 30 Jan 2016.

**Comment by svitalsky** [comment]
Appendix: This is made with Linux Libertine.

![ligatures-2](https://cloud.githubusercontent.com/assets/17103067/12869854/6c70f0e8-cd2b-11e5-8a5a-70cf6dda1a76.png)

**Comment by khaledhosny** [comment]
That is a bug in LuaTeX (or rather whatever font loader you are using). I recently switched Qu from a ligature to a contextual alternate (makes it easy to handle issues like #9 without duplicating the glyphs), and I guess LuaTeX is unable to use this.

**Comment by georgd** [comment]
This is due to LuaTeX not switching on calt by default. I'm getting the
same type of report regularly for EBGaramond. This is fixed by adding
RawFeature=+calt to \defaultfontfeatures if you use fontspec.
Am 07.02.2016 06:41 schrieb "Khaled Hosny" <notifications@github.com>:

**Comment by svitalsky** [comment]
Thank you Georg, this works.

**Comment by georgd** [comment]
The culprit lines might be in luaotfload rather than in LuaTeX itself. In
ConTeXt calt isn't on by default as well.
Am 07.02.2016 12:54 schrieb "svitalsky" <notifications@github.com>:

**Comment by svitalsky** [comment]
However, the solution given above only works if I do not use another fontspec option, "Renderer=Basic", which is required — as stated in the microtype package documentation — in case I want to use the microtype package "tracking" feature in LuaLaTeX. So I guess I'll have to decide whether to use Libertinus without tracking or Libertine with tracking (I only wish I understood better what are — from the common user's point of view — the bugs in Libertine addressed in Libertinus, hence being able to make the decision more competently).

**Comment by khaledhosny** [comment]
See https://github.com/khaledhosny/libertinus/blob/master/FONTLOG.txt#L45

**Comment by Kiwiengr** [comment]
The old problem with LuaLaTeX contextual ligatures (Qu and Qv do not show the Q.long glyph) has a solution for my MiKTeX 2.9 system which includes fontspec-luatex v2.7f, Biblatex v3.14, main font LibertinusSerif.otf v7.040, and (the more powerful) Polyglossia v1.46 in place of Babel. I noticed that someone had made a fix for essentially the same problem I was having, but in a XeteX EBGaramond context. I tried the same thing. Success! Here are the details: If you are using \addfontfeatures{Contextuals=Alternate} immediately after \begin{document}, remove it. Add Contextuals = Alternate to \setmainfont{LibertinusSerif}[...]. E.g., ...Contextuals=Alternate, Extension =.otf]. N.B. I am stuck on the above-mentioned Miktex versions because after one package update a couple of years ago, my current project (a large scientific tome in multiple parts) would not compile, so I had to revert. Therefore, other than font updates (via Windows11 system .otf fonts), I will not be updating again until this project is completed. This has not at all dampened my enthusiasm for LuaLatex, which has been able to cope with everything I have thrown at it in the writing department.  BTW, want to put out a shout to Maïeul Rouquette for his tres excellent indextools. Feedback invited. AR.
