### ISSUE TITLE
U+02E5–U+02E9 should composed in sequence for contour tones

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#30]
Several fonts such as Arial, Segoe UI, Times New Roman, DejaVu fonts, Charis SIL and Doulos SIL can do [this](https://en.wikipedia.org/wiki/Tone_letter), but Libertinus font cannot.

**Comment by Crissov** [comment]
This has also been requested in a comment to [bug #300 of Linux Libertine on SF.net](https://sourceforge.net/p/linuxlibertine/bugs/300/). The original bug is about U+1DC4–9  from the [Combining Diacritical Marks Supplement](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks_Supplement) block.

**Comment by khaledhosny** [comment]
I’m tempted to close this as WONTFIX, not every font can/should support every character in Unicode and I don’t see what much value support tone letters in Libertinus would added, you need at most one font to support them and they should then work with any font.

**Comment by Crissov** [comment]
Complete and correct IPA coverage would be a nice feature that not many typefaces possess. This issue would be a small part of that goal, which could get a label or milestone of its own (and probably low priority). WONTFIX sounds so alienating and final.

**Comment by khaledhosny** [comment]
Completeness for completeness sake is just waste of resources. That being said, patches are welcome :) (and here it should be as easy as copying the glyphs and OTL rules from another font with a compatible license).

**Comment by Crissov** [comment]
Completeness assures potential users that they won’t run into common problems, even if they’d never need the missing or malformed glyphs. 

Character coverage (letters and punctuation) is not all, though, because sometimes you need adjusted glyphs or custom font features to really claim proper support for a certain writing system or technical notation. I don’t know whether there is an openly available test suite or certification programme for that, but I hope there is. I would like to see a badge that is awarded to all typefaces that properly cover the writing systems of all official languages of the European Union, for instance, or the Pan-Nigerian Alphabet or, to get back on topic, everything frequently needed in linguistics (IPA, UPA, ∅, ⟨⟩ or 〈〉, …) or other sciences – although “mathematics” covers a lot already.

Anyhow, is the SIL license compatible? As noted in the OP, their fonts usually support this particular use case.

**Comment by moyogo** [comment]
The tone letters in DejaVu fonts are public domain since they were drawn from scratch.

**Comment by khaledhosny** [comment]
I still think I’m better off just dropping the tone letters completely, but if someone want to copy the glyphs from DeJaVu (together with any relevant lookups) then I don’t mind merging it.

**Comment by khaledhosny** [comment]
A year passed and no one did the copying from DejaVu, so I went ahead and just removed them. No support (and thus allowing applications to do font fallback) is better than incomplete support.
