### ISSUE TITLE
Non-matching slots in the PUA

### ISSUE THREAD

**Issue by sieversMartin** [khaledhosny/libertinus#35]
Inside the PUA starting at E000 there are some slots not used for the same character. Have a look at Unicode index E00D and compare e.g. the italic serif version with the regular one.

Is this an intended behaviour?

**Comment by khaledhosny** [comment]
Yes, the general direction is to have as few PUA characters as possible, alternate glyphs should always be accessible though OpenType features not PUA. Some of the remaining PUA characters are there because I didn’t figure out what features they are used in.

**Comment by sieversMartin** [comment]
Am 07.04.2016 um 13:34 schrieb Khaled Hosny:
> Yes, the general direction is to have as few PUA characters as possible,
> alternate glyphs should always be accessible though OpenType features
> not PUA. Some of the remaining PUA characters are there because I didn’t
> figure out what features they are used in.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/khaledhosny/libertinus/issues/35#issuecomment-206825767>
> 

I totally agree with what you say about PUA and OpenType features.

However, I am a bit puzzled. So you say it is intented that I get a "y"
instead of a "public domain" glyph just by switching from regular to
italic? Sounds weird to me.

Best
Martin

-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by khaledhosny** [comment]
That is the price of using PUA, anything can go there and that is why I’m moving way from it.

**Comment by KrasnayaPloshchad** [comment]
Some M$ Windows softwares has bad or very limited appearences to process OpenType feature, those PUA glyphs removed from Libertinus may are intended to give treatments for them, as I know, these program include: MS Office 2013 Simp. Chinese version, WPS Office and LO for Windows.

**Comment by mgavioli** [comment]
@khaledhosny : This issue is closed since two year and with good reason; the PUA is a curse and the world would be better without (the misuse which has been made of) it. However, life is not as easy as one would like and I believe some case could be done for reconsidering.

**1. OpenType feature access**: It is true that many general-purpose text-and-word applications now give the user access to OT features (the recent addition to LibreOffice, 21 years after the OT initial specification, was a life saver for me).

However, lots of special-purpose, often mission-critical, applications still lack that possibility. For instance, all Qt-based applications (unless they by-pass or supplement the default and hidden harfbuzz setup provided by Qt, which is very far from trivial); or, to my experience, the most widely used cartographic applications or music notation applications.

All these software give the user no access to rather simple but typographically important features like small caps or lower-case numerals. Currently those users have no way to benefit from Libertinus major features and a radical change does not seem incoming.

It can be said that this is a problem of those other applications, not of Libertinus; however, in many cases, those are the applications which potential Libertinus users **have** to use, because of their relevance in their respective fields and Libertinus is leaving those users 'in the middle of the ford'.

**2. Compatibility with Linux Libertine**: I for one have a corpus of some thousands of files using Linux Libertine (before I discovered Libertinus) heavily relying on Linux Libertine PUA glyphs (for reason 1. above).

While in my case all LibreOffice files can be easily upgraded -- in them I luckily used the G version of Linux Libertine, to avoid coding PUA glyphs directly, and the change to Libertinus would mostly be a matter of changing the styles --, all other files (mostly music notation in my case) simply cannot be moved to Libertinus, as they had and have no other way than relying on PUA encoding directly.

I am reasonably sure I am not alone in this.
_  _  _  _  _

To make short a long story, my proposal is to restore the PUA encoding of glyph variants, **as it was in the original Libertine fonts** (with its oddities, 'bugs' and all), without removing anything from the feature tables of Libertinus and with the 'blood pact' not to extend the PUA any more in any way, keeping it for backward compatibility only.

I am aware this is not optimal but, alas, life is not optimal either...

**Comment by khaledhosny** [comment]
1. For situations like this there are tools like [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) that allow making certain features the default, which though is a bit more work, still much better than using PUA and getting garbage or tofus when the text is shown in a different font for whatever reason, not to mention keeping the semantics of the text intact (so indexing, searching, etc. is not broken).
2. That is even more reason to not use PUA otherwise we are making a pseudo encoding standard that users rely on and expect it to be supported *ad infinitum*. PUA has its uses, but this is explicitly not one of them and I strongly believe in not feeding this trend.

**Comment by mgavioli** [comment]
I am glad I raised this point and that you answered so extensively; I was not aware of tools like `pyftfeafreeze` (I though of making 'frozen-feature' fonts manually, but I never found the time for it).

Now I learned something quite useful. And then, eventually, I agree with you. Thanks!
