### ISSUE TITLE
Braces of different sizes in Libertinus Math

### ISSUE THREAD

**Issue by ralfwimmer** [khaledhosny/libertinus#38]
Dear Khaled,

the package amsmath allows to have braces of different sizes using `\bigl\{ ... \bigr\}`. The spacing seems to be wrong and the style of the larger braces (curved) does not match that of the smaller ones (straight). The long vertical bar `\big|` is larger than the corresponding braces. See for example the following document:

`\documentclass{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\usepackage{amsmath}

\begin{document}
[
   \bigl{ { s\in S\,|\, f(s) = f(t)}\,\big|\,t\in S\bigr}
]

\setmainfont[Mapping=tex-text]{Libertinus Serif}
\setsansfont[Mapping=tex-text]{Libertinus Sans}
\setmathfont{Libertinus Math}

[
   \bigl{ { s\in S\,|\, f(s) = f(t)}\,\big|\,t\in S\bigr}
]
\end{document}`

which yields (using xelatex): 

![font](https://cloud.githubusercontent.com/assets/14362323/15112314/990121c2-15ed-11e6-83b8-262aa0ad6bec.jpg)

Let me thank you for the great work you did on the beautful Libertinus font!

With best regards
    Ralf.

**Comment by timtro** [comment]
I confirmed this in LuaLaTeX. However, the MWE is strangely missing some slashes (and isn't quite minimal). Khaled, to spare you the trouble, I'm reposting the corrected MWE:

```
%!TEX program = lualatex
%

\documentclass{article}
\usepackage{unicode-math}

\begin{document}

\[
   \bigl\{ \{ s\in S\,|\, f(s) = f(t)\}\,\big|\,t\in S\bigr\}
\]

\setmathfont{Libertinus Math}
\[
   \bigl\{ \{ s\in S\,|\, f(s) = f(t)\}\,\big|\,t\in S\bigr\}
\]

\end{document}
```

**Comment by khaledhosny** [comment]
Yes, this needs to be cleaned up. I’m thinking of using the style of the larger braces for the base size as well (and fix the spacing of course), what do you think?

**Comment by timtro** [comment]
Of course this is purely subjective, but I admit to not being a fan of the shape of the braces in Libertine/us---especially the `\big` size. To my eye, they are a distraction in paragraphs where I define a lot of sets and functions together because the visual clash of the weights. 

I have been using the `range` option is `\setmathfont` to import Latin Modern Math braces, which aren't a perfect match for Libertinus, but not bad.

Cf. The CMR delimiters vs. Libertinus:
![screenshot from 2016-05-10 17-13-47](https://cloud.githubusercontent.com/assets/329007/15162757/9ddb3bc0-16d2-11e6-8a40-fb7bbc4049b6.png)

I find Libertinus braces a bit too slender at the midpoint compared to the weight of the parens, brackets and even alphabetical characters. I also think they aren't visually dissimilar enough to the square brackets and I've found them confusing in expressions that mix the two. I think that is mainly due to the vertical flatness. Using the overall curvature as a metric, I feel that braces should be somewhere between the brackets and parens, which distinguishes them at a glance.

As I said, this is purely subjective and I'm not under the impression that this is a democratic endeavour. Please make the choices you feel are right. Thank you for asking your adoring public.

(Code for reference)
```
%!TEX program = lualatex
%

\documentclass{article}
\usepackage{unicode-math}

\begin{document}

\centering CM:
\[
  (\{[\mathup{MmOo}
    \quad \big(\big\{\big[\mathup{MmOo}
    \quad \Big(\Big\{\Big[\mathup{MmOo}
    \quad \bigg(\bigg\{\bigg[\mathup{MmOo}
    \quad  \Bigg(\Bigg\{\Bigg[\mathup{MmOo}
\]

\setmainfont{Libertinus Serif}
\setmathfont{Libertinus Math}
Libertinus:
\[
  (\{[\mathup{MmOo}
    \quad \big(\big\{\big[\mathup{MmOo}
    \quad \Big(\Big\{\Big[\mathup{MmOo}
    \quad \bigg(\bigg\{\bigg[\mathup{MmOo}
    \quad  \Bigg(\Bigg\{\Bigg[\mathup{MmOo}
\]

\end{document}
```

**Comment by khaledhosny** [comment]
I heard recently that there is a saying in type design, “pick your favourite 2 or 3 glyphs and kill them” or something like that. And the big braces being my most favourite, I’m starting with them :)

**Comment by khaledhosny** [comment]
I’m going to design new big braces based on the base Libertine one, I hope it is not not a very bad base.

**Comment by timtro** [comment]
Well, you see, now I feel bad for having denigrating the braces---your favourite glyphs. This is how I repay the man that gave me my favourite font after years of waiting.

About the Libertinus braces, I do like the sort of appearance of having been written with a split nib varying the line width along the contour of the character. It is that appearance which the CM braces lack, which motivated my comment that the CM braces are not a perfect match for the Roman alphabetic glyphs.

To be clear about my criticisms, I summarise them in two points. (1) If a line is drawn connecting the inner top and bottom points (that is, the two points that would be rightmost in the left brace `{` ), the nodes of the middle cusp seem too close to that line, making the glyph appear too flat. Being too flat seems aesthetically displeasing, in addition to making the character too easily confused with the square-bracket. (2) the weight of the line around the cusp is too light. I don't think it should be thinner than the leftmost vertical line of the capital M.

**Comment by alerque** [comment]
I'm not a regular user of the math symbols so my say might not even be worth 2¢, but I agree the big brace leaves something to be desired. In the samples above, besides the flatness, the spacing seems to be a major difference. Both the regular size braces and the other large symbols have considerably more space before and after the actual symbols wheras the large braces are quite cosy with their surroundings.

**Comment by khaledhosny** [comment]
The shape should be better now. Not sure about the spacing though, so please test and let me know if there is anything still missing here.
