### ISSUE TITLE
Printing Problems

### ISSUE THREAD

**Issue by Ad-Astm** [khaledhosny/libertinus#62]
A number of printing problems have been reported in the Linux Libertine bug tracker. Here is another report of characters printing incorrectly i.e. looking distorted:
https://indesignsecrets.com/topic/book-printing-big-problem

Apparently, using the graphite version of Linux  Librtine fonts helped:
https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1018069

**Comment by khaledhosny** [comment]
Can you reproduce this yourself with Libertinus? Looks like a hinting issue, but I need someone being able to reproduce this to do any meaningful debugging.

**Comment by alerque** [comment]
I've seen nothing like the symptoms described in that thread using *Libertinus Serif* and I've published several full length books and literally thousands of shorter print documents. I suspect the OP was up against some bug specific to his OS's shaping engine and/or the old version of the original font series he was using.

If there are specific reports from the *Linux Libertine* tracker that you can duplicate using *Libertinus* equivalents then by all means lets have a detailed report, but this issue seems un-actionable to me because there isn't anything specific to fix. If we can point to something that's specifically known to be broken then we could track it down...

**Comment by khaledhosny** [comment]
The screenshots suggests this is a hinting issue, and I recall old versions `ttfautohint` causing similar printing issues with buggy printers (Linux Libertine seems to have used it), but Libertinus does not even provide TTF files lets alone autohinted ones, so I’m curious to know if OP actually suffering from this or just letting us know about possible issues?

**Comment by khaledhosny** [comment]
From this [the comment](https://indesignsecrets.com/topic/book-printing-big-problem#post-73772), the TTF files were used, which further confirms that this is the ttfauthint issue. Since we don’t provide any TTF files, the issue is irrelevant to us.
