### ISSUE TITLE
Eng looks different in Libertinus Serif

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#97]
The shape of Latin Eng looks different in Libertinus Serif while switching different font weight and styles.
![1](https://i.imgur.com/1s1fVVm.png)
See: https://sourceforge.net/p/linuxlibertine/bugs/328/

**Comment by khaledhosny** [comment]
Consistency is overrated. Related: http://typedrawers.com/discussion/2406/capital-eng.

**Comment by mgavioli** [comment]
For what it is worth, Gentium Plus encodes:

1. in the U+014A BMP slot the 'n + j' (the one used by Libertinus Regular),
2. in an unencoded variant ("Eng.UCStyle") the 'N + J' (the one used by Libertinus Semi-bold)
3. in an unencoded variant ("Eng.BaselineHook") the 'n + j with base line hook' in (currently not used in Libertinus)
4. in an unencoded variant ("Eng.Kom") the 'n + j shortened' form.

![issue_097_screenshot_01](https://user-images.githubusercontent.com/1420743/36419260-b315d896-1631-11e8-9940-685cdcaf5455.png)

The last three are probably access via some feature or localisation, but I could not find which.

I suppose a reasonable solution could be to follow Gentium example for 1. and 2. and ignore 3. and 4. (at least for the time being).

Comments?

**Comment by khaledhosny** [comment]
I think @moyogo might have some input here, but I think we need to have either the N or n form as default for all style, and provide the other one as alternate (stylistic set, but I think there is also some preference for one or the other depending on the locale so we might want to hock it up in a `locl` feature as well).

**Comment by moyogo** [comment]
One strategy is to have the Eng LC style as the default since there are several African languages that have it as a preferred form and some don’t have OT language tags and set the Eng.UCStyle as locl form for Sami languages (and maybe neighbouring Nordic languages) since those do have OT languages tags and as a stylistic set.

The users I’ve met are unfamiliar with the Baseline hook form and I guess we can trust the SIL with the Kom form.
